# Generated by Django 4.0.2 on 2022-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Сategory',
        ),
    ]
