# Generated by Django 4.0.2 on 2022-03-15 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_сategory_parent_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_messege',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
