# Generated by Django 4.0.2 on 2022-03-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_user_time_messege'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Messege',
        ),
    ]
