# Generated by Django 4.0.2 on 2022-03-16 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_rename_user_messege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messege',
            name='time_messege',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
