# Generated by Django 4.0.2 on 2022-03-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_messege_time_messege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messege',
            name='time_messege',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
