# Generated by Django 4.0.2 on 2022-03-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_messege_time_messege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('chat_id', models.IntegerField(verbose_name='id_chat')),
            ],
        ),
        migrations.AlterField(
            model_name='messege',
            name='message',
            field=models.CharField(max_length=500, verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, verbose_name='Имя')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('online', models.BooleanField(default=False, verbose_name='Статус')),
                ('chats', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='firstapp.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='message_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.messege'),
        ),
    ]
