# Generated by Django 4.0.2 on 2022-03-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_chat_alter_messege_message_user_chat_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_chat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='firstapp.user'),
        ),
        migrations.AddField(
            model_name='messege',
            name='message_chat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='firstapp.chat'),
        ),
    ]
