# Generated by Django 4.0.2 on 2022-03-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_remove_chat_message_chat_remove_user_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='firstapp.user'),
        ),
        migrations.AlterField(
            model_name='messege',
            name='message_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='firstapp.chat'),
        ),
    ]
