# Generated by Django 4.0.2 on 2022-03-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_chat_users_alter_messege_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messege',
            name='message_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='firstapp.chat'),
        ),
    ]
